// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package cinder

import (
	"database/sql"
)

type Quota struct {
	ID        int32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
	Deleted   sql.NullBool
	ProjectID sql.NullString
	Resource  string
	HardLimit sql.NullInt32
	Allocated sql.NullInt32
}

type QuotaUsage struct {
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	DeletedAt     sql.NullTime
	Deleted       sql.NullBool
	ID            int32
	ProjectID     sql.NullString
	Resource      sql.NullString
	InUse         int32
	Reserved      int32
	UntilRefresh  sql.NullInt32
	RacePreventer sql.NullBool
}

type Service struct {
	CreatedAt            sql.NullTime
	UpdatedAt            sql.NullTime
	DeletedAt            sql.NullTime
	Deleted              sql.NullBool
	ID                   int32
	Host                 sql.NullString
	Binary               sql.NullString
	Topic                sql.NullString
	ReportCount          int32
	Disabled             sql.NullBool
	AvailabilityZone     sql.NullString
	DisabledReason       sql.NullString
	ModifiedAt           sql.NullTime
	RpcCurrentVersion    sql.NullString
	ObjectCurrentVersion sql.NullString
	ReplicationStatus    sql.NullString
	Frozen               sql.NullBool
	ActiveBackendID      sql.NullString
	ClusterName          sql.NullString
	Uuid                 sql.NullString
}

type Snapshot struct {
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
	DeletedAt          sql.NullTime
	Deleted            sql.NullBool
	ID                 string
	VolumeID           string
	UserID             sql.NullString
	ProjectID          sql.NullString
	Status             sql.NullString
	Progress           sql.NullString
	VolumeSize         sql.NullInt32
	ScheduledAt        sql.NullTime
	DisplayName        sql.NullString
	DisplayDescription sql.NullString
	ProviderLocation   sql.NullString
	EncryptionKeyID    sql.NullString
	VolumeTypeID       string
	CgsnapshotID       sql.NullString
	ProviderID         sql.NullString
	ProviderAuth       sql.NullString
	GroupSnapshotID    sql.NullString
	UseQuota           bool
}

type Volume struct {
	CreatedAt                 sql.NullTime
	UpdatedAt                 sql.NullTime
	DeletedAt                 sql.NullTime
	Deleted                   sql.NullBool
	ID                        string
	Ec2ID                     sql.NullString
	UserID                    sql.NullString
	ProjectID                 sql.NullString
	Host                      sql.NullString
	Size                      sql.NullInt32
	AvailabilityZone          sql.NullString
	Status                    sql.NullString
	AttachStatus              sql.NullString
	ScheduledAt               sql.NullTime
	LaunchedAt                sql.NullTime
	TerminatedAt              sql.NullTime
	DisplayName               sql.NullString
	DisplayDescription        sql.NullString
	ProviderLocation          sql.NullString
	ProviderAuth              sql.NullString
	SnapshotID                sql.NullString
	VolumeTypeID              string
	SourceVolid               sql.NullString
	Bootable                  sql.NullBool
	ProviderGeometry          sql.NullString
	NameID                    sql.NullString
	EncryptionKeyID           sql.NullString
	MigrationStatus           sql.NullString
	ReplicationStatus         sql.NullString
	ReplicationExtendedStatus sql.NullString
	ReplicationDriverData     sql.NullString
	ConsistencygroupID        sql.NullString
	ProviderID                sql.NullString
	Multiattach               sql.NullBool
	PreviousStatus            sql.NullString
	ClusterName               sql.NullString
	GroupID                   sql.NullString
	ServiceUuid               sql.NullString
	SharedTargets             sql.NullBool
	UseQuota                  bool
}

type VolumeAttachment struct {
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	DeletedAt      sql.NullTime
	Deleted        sql.NullBool
	ID             string
	VolumeID       string
	AttachedHost   sql.NullString
	InstanceUuid   sql.NullString
	Mountpoint     sql.NullString
	AttachTime     sql.NullTime
	DetachTime     sql.NullTime
	AttachMode     sql.NullString
	AttachStatus   sql.NullString
	ConnectionInfo sql.NullString
	Connector      sql.NullString
}

type VolumeType struct {
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	Deleted     sql.NullBool
	ID          string
	Name        sql.NullString
	QosSpecsID  sql.NullString
	IsPublic    sql.NullBool
	Description sql.NullString
}
