// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package manila

import (
	"database/sql"
)

type AvailabilityZone struct {
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
	Deleted   sql.NullString
	ID        string
	Name      sql.NullString
}

type Share struct {
	CreatedAt                        sql.NullTime
	UpdatedAt                        sql.NullTime
	DeletedAt                        sql.NullTime
	Deleted                          sql.NullString
	ID                               string
	UserID                           sql.NullString
	ProjectID                        sql.NullString
	Size                             sql.NullInt32
	DisplayName                      sql.NullString
	DisplayDescription               sql.NullString
	SnapshotID                       sql.NullString
	ShareProto                       sql.NullString
	IsPublic                         sql.NullBool
	SnapshotSupport                  sql.NullBool
	ShareGroupID                     sql.NullString
	SourceShareGroupSnapshotMemberID sql.NullString
	TaskState                        sql.NullString
	ReplicationType                  sql.NullString
	CreateShareFromSnapshotSupport   sql.NullBool
	RevertToSnapshotSupport          sql.NullBool
	MountSnapshotSupport             sql.NullBool
	IsSoftDeleted                    bool
	ScheduledToBeDeletedAt           sql.NullTime
	SourceBackupID                   sql.NullString
}

type ShareInstance struct {
	CreatedAt           sql.NullTime
	UpdatedAt           sql.NullTime
	DeletedAt           sql.NullTime
	Deleted             sql.NullString
	ID                  string
	ShareID             sql.NullString
	Host                sql.NullString
	Status              sql.NullString
	ScheduledAt         sql.NullTime
	LaunchedAt          sql.NullTime
	TerminatedAt        sql.NullTime
	ShareNetworkID      sql.NullString
	ShareServerID       sql.NullString
	AvailabilityZoneID  sql.NullString
	AccessRulesStatus   sql.NullString
	ReplicaState        sql.NullString
	ShareTypeID         sql.NullString
	CastRulesToReadonly bool
	Progress            sql.NullString
	MountPointName      sql.NullString
}

type ShareType struct {
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	Deleted     sql.NullString
	ID          string
	Name        sql.NullString
	IsPublic    sql.NullBool
	Description sql.NullString
}
