// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package neutron

import (
	"context"
	"database/sql"
)

const GetAgents = `-- name: GetAgents :many
SELECT
    a.id,
    a.agent_type,
    a.` + "`" + `binary` + "`" + ` as service,
    a.host as hostname,
    CASE
        WHEN a.admin_state_up = 1 THEN 'enabled'
        ELSE 'disabled'
    END as admin_state,
    a.availability_zone as zone,
    CASE
        WHEN TIMESTAMPDIFF(SECOND, a.heartbeat_timestamp, NOW()) <= 75 THEN 1
        ELSE 0
    END as alive
FROM
    agents a
`

type GetAgentsRow struct {
	ID         string
	AgentType  string
	Service    string
	Hostname   string
	AdminState string
	Zone       sql.NullString
	Alive      int32
}

func (q *Queries) GetAgents(ctx context.Context) ([]GetAgentsRow, error) {
	rows, err := q.db.QueryContext(ctx, GetAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAgentsRow
	for rows.Next() {
		var i GetAgentsRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentType,
			&i.Service,
			&i.Hostname,
			&i.AdminState,
			&i.Zone,
			&i.Alive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetFloatingIPs = `-- name: GetFloatingIPs :many
SELECT
    fip.id,
    fip.floating_ip_address,
    fip.floating_network_id,
    fip.project_id,
    fip.router_id,
    fip.status,
    fip.fixed_ip_address
FROM
    floatingips fip
`

type GetFloatingIPsRow struct {
	ID                string
	FloatingIpAddress string
	FloatingNetworkID string
	ProjectID         sql.NullString
	RouterID          sql.NullString
	Status            sql.NullString
	FixedIpAddress    sql.NullString
}

func (q *Queries) GetFloatingIPs(ctx context.Context) ([]GetFloatingIPsRow, error) {
	rows, err := q.db.QueryContext(ctx, GetFloatingIPs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFloatingIPsRow
	for rows.Next() {
		var i GetFloatingIPsRow
		if err := rows.Scan(
			&i.ID,
			&i.FloatingIpAddress,
			&i.FloatingNetworkID,
			&i.ProjectID,
			&i.RouterID,
			&i.Status,
			&i.FixedIpAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetHARouterAgentPortBindingsWithAgents = `-- name: GetHARouterAgentPortBindingsWithAgents :many
SELECT
    ha.router_id,
    ha.l3_agent_id,
    ha.state,
    a.host as agent_host,
    a.admin_state_up as agent_admin_state_up,
    a.heartbeat_timestamp as agent_heartbeat_timestamp
FROM
    ha_router_agent_port_bindings ha
    LEFT JOIN agents a ON ha.l3_agent_id = a.id
`

type GetHARouterAgentPortBindingsWithAgentsRow struct {
	RouterID                string
	L3AgentID               sql.NullString
	State                   NullHaRouterAgentPortBindingsState
	AgentHost               sql.NullString
	AgentAdminStateUp       sql.NullBool
	AgentHeartbeatTimestamp sql.NullTime
}

func (q *Queries) GetHARouterAgentPortBindingsWithAgents(ctx context.Context) ([]GetHARouterAgentPortBindingsWithAgentsRow, error) {
	rows, err := q.db.QueryContext(ctx, GetHARouterAgentPortBindingsWithAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHARouterAgentPortBindingsWithAgentsRow
	for rows.Next() {
		var i GetHARouterAgentPortBindingsWithAgentsRow
		if err := rows.Scan(
			&i.RouterID,
			&i.L3AgentID,
			&i.State,
			&i.AgentHost,
			&i.AgentAdminStateUp,
			&i.AgentHeartbeatTimestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetNetworkIPAvailabilitiesTotal = `-- name: GetNetworkIPAvailabilitiesTotal :many
SELECT
    s.name AS subnet_name,
    n.name AS network_name,
    s.id   AS subnet_id,
    n.id   AS network_id,
    ap.first_ip,
    ap.last_ip,
    s.project_id,
    s.cidr,
    s.ip_version
FROM subnets s
JOIN networks n
    ON s.network_id = n.id
LEFT JOIN ipallocationpools ap
    ON s.id = ap.subnet_id
GROUP BY
    s.id,
    n.id,
    s.project_id,
    s.cidr,
    s.ip_version,
    s.name,
    n.name,
    ap.first_ip,
    ap.last_ip
`

type GetNetworkIPAvailabilitiesTotalRow struct {
	SubnetName  sql.NullString
	NetworkName sql.NullString
	SubnetID    string
	NetworkID   string
	FirstIp     sql.NullString
	LastIp      sql.NullString
	ProjectID   sql.NullString
	Cidr        string
	IpVersion   int32
}

func (q *Queries) GetNetworkIPAvailabilitiesTotal(ctx context.Context) ([]GetNetworkIPAvailabilitiesTotalRow, error) {
	rows, err := q.db.QueryContext(ctx, GetNetworkIPAvailabilitiesTotal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNetworkIPAvailabilitiesTotalRow
	for rows.Next() {
		var i GetNetworkIPAvailabilitiesTotalRow
		if err := rows.Scan(
			&i.SubnetName,
			&i.NetworkName,
			&i.SubnetID,
			&i.NetworkID,
			&i.FirstIp,
			&i.LastIp,
			&i.ProjectID,
			&i.Cidr,
			&i.IpVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetNetworkIPAvailabilitiesUsed = `-- name: GetNetworkIPAvailabilitiesUsed :many
SELECT
    s.id AS subnet_id,
    s.name AS subnet_name,
    s.cidr,
    s.ip_version,
    s.project_id,
    n.id AS network_id,
    n.name AS network_name,
    CAST(COUNT(ipa.ip_address) AS SIGNED) AS allocation_count
FROM subnets s
    LEFT JOIN ipallocations ipa ON ipa.subnet_id = s.id
    LEFT JOIN networks n ON s.network_id = n.id
GROUP BY s.id, n.id
`

type GetNetworkIPAvailabilitiesUsedRow struct {
	SubnetID        string
	SubnetName      sql.NullString
	Cidr            string
	IpVersion       int32
	ProjectID       sql.NullString
	NetworkID       sql.NullString
	NetworkName     sql.NullString
	AllocationCount int64
}

func (q *Queries) GetNetworkIPAvailabilitiesUsed(ctx context.Context) ([]GetNetworkIPAvailabilitiesUsedRow, error) {
	rows, err := q.db.QueryContext(ctx, GetNetworkIPAvailabilitiesUsed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNetworkIPAvailabilitiesUsedRow
	for rows.Next() {
		var i GetNetworkIPAvailabilitiesUsedRow
		if err := rows.Scan(
			&i.SubnetID,
			&i.SubnetName,
			&i.Cidr,
			&i.IpVersion,
			&i.ProjectID,
			&i.NetworkID,
			&i.NetworkName,
			&i.AllocationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetNetworks = `-- name: GetNetworks :many
SELECT
    n.id,
    n.name,
    n.project_id,
    n.status,
    ns.network_type as provider_network_type,
    ns.physical_network as provider_physical_network,
    COALESCE(CAST(ns.segmentation_id AS CHAR), '') as provider_segmentation_id,
    COALESCE(CAST(GROUP_CONCAT(DISTINCT s.id) AS CHAR), '') as subnets,
    CASE
        WHEN en.network_id IS NOT NULL THEN 1
        ELSE 0
    END AS is_external,
    CASE
        WHEN shared_rbacs.object_id IS NOT NULL THEN 1
        ELSE 0
    END AS is_shared,
    COALESCE(CAST(GROUP_CONCAT(DISTINCT t.tag) AS CHAR), '') as tags
FROM
    networks n
    LEFT JOIN networksegments ns ON n.id = ns.network_id
    LEFT JOIN subnets s ON n.id = s.network_id
    LEFT JOIN externalnetworks en ON n.id = en.network_id
    LEFT JOIN networkrbacs shared_rbacs ON n.id = shared_rbacs.object_id AND shared_rbacs.target_project = '*' AND shared_rbacs.action = 'access_as_shared'
    LEFT JOIN standardattributes sa ON n.standard_attr_id = sa.id
    LEFT JOIN tags t ON sa.id = t.standard_attr_id
GROUP BY
    n.id,
    n.name,
    n.project_id,
    n.status,
    ns.network_type,
    ns.physical_network,
    ns.segmentation_id,
    en.network_id,
    shared_rbacs.object_id
`

type GetNetworksRow struct {
	ID                      string
	Name                    sql.NullString
	ProjectID               sql.NullString
	Status                  sql.NullString
	ProviderNetworkType     sql.NullString
	ProviderPhysicalNetwork sql.NullString
	ProviderSegmentationID  interface{}
	Subnets                 interface{}
	IsExternal              int32
	IsShared                int32
	Tags                    interface{}
}

func (q *Queries) GetNetworks(ctx context.Context) ([]GetNetworksRow, error) {
	rows, err := q.db.QueryContext(ctx, GetNetworks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNetworksRow
	for rows.Next() {
		var i GetNetworksRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProjectID,
			&i.Status,
			&i.ProviderNetworkType,
			&i.ProviderPhysicalNetwork,
			&i.ProviderSegmentationID,
			&i.Subnets,
			&i.IsExternal,
			&i.IsShared,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetPorts = `-- name: GetPorts :many
SELECT
    p.id,
    p.mac_address,
    p.device_owner,
    p.status,
    p.network_id,
    p.admin_state_up,
    p.ip_allocation,
    b.vif_type as binding_vif_type,
    COALESCE(CAST(GROUP_CONCAT(ia.ip_address ORDER BY ia.ip_address) AS CHAR), '') as fixed_ips
FROM
    ports p
    LEFT JOIN ml2_port_bindings b ON p.id = b.port_id
    LEFT JOIN ipallocations ia ON p.id = ia.port_id
GROUP BY
    p.id,
    p.mac_address,
    p.device_owner,
    p.status,
    p.network_id,
    p.admin_state_up,
    p.ip_allocation,
    b.vif_type
`

type GetPortsRow struct {
	ID             string
	MacAddress     string
	DeviceOwner    string
	Status         string
	NetworkID      string
	AdminStateUp   bool
	IpAllocation   sql.NullString
	BindingVifType sql.NullString
	FixedIps       interface{}
}

func (q *Queries) GetPorts(ctx context.Context) ([]GetPortsRow, error) {
	rows, err := q.db.QueryContext(ctx, GetPorts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPortsRow
	for rows.Next() {
		var i GetPortsRow
		if err := rows.Scan(
			&i.ID,
			&i.MacAddress,
			&i.DeviceOwner,
			&i.Status,
			&i.NetworkID,
			&i.AdminStateUp,
			&i.IpAllocation,
			&i.BindingVifType,
			&i.FixedIps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetQuotas = `-- name: GetQuotas :many
SELECT
    q.project_id,
    q.resource,
    q.` + "`" + `limit` + "`" + `
FROM
    quotas q
WHERE
    q.project_id IS NOT NULL
`

type GetQuotasRow struct {
	ProjectID sql.NullString
	Resource  sql.NullString
	Limit     sql.NullInt32
}

func (q *Queries) GetQuotas(ctx context.Context) ([]GetQuotasRow, error) {
	rows, err := q.db.QueryContext(ctx, GetQuotas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetQuotasRow
	for rows.Next() {
		var i GetQuotasRow
		if err := rows.Scan(&i.ProjectID, &i.Resource, &i.Limit); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetResourceCountsByProject = `-- name: GetResourceCountsByProject :many
SELECT
    project_id,
    'floatingip' as resource,
    CAST(COUNT(*) AS SIGNED) as cnt
FROM floatingips WHERE project_id IS NOT NULL GROUP BY project_id
UNION ALL
SELECT
    project_id,
    'network' as resource,
    CAST(COUNT(*) AS SIGNED) as cnt
FROM networks WHERE project_id IS NOT NULL GROUP BY project_id
UNION ALL
SELECT
    project_id,
    'port' as resource,
    CAST(COUNT(*) AS SIGNED) as cnt
FROM ports WHERE project_id IS NOT NULL GROUP BY project_id
UNION ALL
SELECT
    project_id,
    'router' as resource,
    CAST(COUNT(*) AS SIGNED) as cnt
FROM routers WHERE project_id IS NOT NULL GROUP BY project_id
UNION ALL
SELECT
    project_id,
    'security_group' as resource,
    CAST(COUNT(*) AS SIGNED) as cnt
FROM securitygroups WHERE project_id IS NOT NULL GROUP BY project_id
UNION ALL
SELECT
    project_id,
    'security_group_rule' as resource,
    CAST(COUNT(*) AS SIGNED) as cnt
FROM securitygrouprules WHERE project_id IS NOT NULL GROUP BY project_id
UNION ALL
SELECT
    project_id,
    'subnet' as resource,
    CAST(COUNT(*) AS SIGNED) as cnt
FROM subnets WHERE project_id IS NOT NULL GROUP BY project_id
UNION ALL
SELECT
    project_id,
    'rbac_policy' as resource,
    CAST(COUNT(*) AS SIGNED) as cnt
FROM networkrbacs WHERE project_id IS NOT NULL GROUP BY project_id
UNION ALL
SELECT
    project_id,
    'subnetpool' as resource,
    CAST(COUNT(*) AS SIGNED) as cnt
FROM subnetpools WHERE project_id IS NOT NULL GROUP BY project_id
`

type GetResourceCountsByProjectRow struct {
	ProjectID sql.NullString
	Resource  string
	Cnt       int64
}

func (q *Queries) GetResourceCountsByProject(ctx context.Context) ([]GetResourceCountsByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, GetResourceCountsByProject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetResourceCountsByProjectRow
	for rows.Next() {
		var i GetResourceCountsByProjectRow
		if err := rows.Scan(&i.ProjectID, &i.Resource, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetRouters = `-- name: GetRouters :many
SELECT
    r.id,
    r.name,
    r.status,
    r.admin_state_up,
    r.project_id,
    COALESCE(p.network_id, '') as external_network_id
FROM
    routers r
    LEFT JOIN ports p ON r.gw_port_id = p.id
`

type GetRoutersRow struct {
	ID                string
	Name              sql.NullString
	Status            sql.NullString
	AdminStateUp      sql.NullBool
	ProjectID         sql.NullString
	ExternalNetworkID string
}

func (q *Queries) GetRouters(ctx context.Context) ([]GetRoutersRow, error) {
	rows, err := q.db.QueryContext(ctx, GetRouters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRoutersRow
	for rows.Next() {
		var i GetRoutersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.AdminStateUp,
			&i.ProjectID,
			&i.ExternalNetworkID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetSecurityGroupCount = `-- name: GetSecurityGroupCount :one
SELECT
    CAST(COUNT(*) AS SIGNED) as cnt
FROM
    securitygroups
`

func (q *Queries) GetSecurityGroupCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, GetSecurityGroupCount)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const GetSubnetPools = `-- name: GetSubnetPools :many
SELECT
    sp.id,
    sp.ip_version,
    sp.max_prefixlen,
    sp.min_prefixlen,
    sp.default_prefixlen,
    sp.project_id,
    sp.name,
    COALESCE(CAST(GROUP_CONCAT(spp.cidr) AS CHAR), '') as prefixes
FROM
    subnetpools sp
    LEFT JOIN subnetpoolprefixes spp ON sp.id = spp.subnetpool_id
GROUP BY
    sp.id,
    sp.ip_version,
    sp.max_prefixlen,
    sp.min_prefixlen,
    sp.default_prefixlen
`

type GetSubnetPoolsRow struct {
	ID               string
	IpVersion        int32
	MaxPrefixlen     int32
	MinPrefixlen     int32
	DefaultPrefixlen int32
	ProjectID        sql.NullString
	Name             sql.NullString
	Prefixes         interface{}
}

func (q *Queries) GetSubnetPools(ctx context.Context) ([]GetSubnetPoolsRow, error) {
	rows, err := q.db.QueryContext(ctx, GetSubnetPools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubnetPoolsRow
	for rows.Next() {
		var i GetSubnetPoolsRow
		if err := rows.Scan(
			&i.ID,
			&i.IpVersion,
			&i.MaxPrefixlen,
			&i.MinPrefixlen,
			&i.DefaultPrefixlen,
			&i.ProjectID,
			&i.Name,
			&i.Prefixes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetSubnets = `-- name: GetSubnets :many
SELECT
    s.id,
    s.name,
    s.cidr,
    s.gateway_ip,
    s.network_id,
    s.project_id,
    s.enable_dhcp,
    COALESCE(CAST(GROUP_CONCAT(DISTINCT d.address) AS CHAR), '') as dns_nameservers,
    s.subnetpool_id,
    COALESCE(CAST(GROUP_CONCAT(DISTINCT t.tag) AS CHAR), '') as tags
FROM
    subnets s
    LEFT JOIN dnsnameservers d ON s.id = d.subnet_id
    LEFT JOIN standardattributes sa ON s.standard_attr_id = sa.id
    LEFT JOIN tags t ON sa.id = t.standard_attr_id
GROUP BY
    s.id,
    s.name,
    s.cidr,
    s.gateway_ip,
    s.network_id,
    s.project_id,
    s.enable_dhcp,
    s.subnetpool_id
`

type GetSubnetsRow struct {
	ID             string
	Name           sql.NullString
	Cidr           string
	GatewayIp      sql.NullString
	NetworkID      string
	ProjectID      sql.NullString
	EnableDhcp     sql.NullBool
	DnsNameservers interface{}
	SubnetpoolID   sql.NullString
	Tags           interface{}
}

func (q *Queries) GetSubnets(ctx context.Context) ([]GetSubnetsRow, error) {
	rows, err := q.db.QueryContext(ctx, GetSubnets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubnetsRow
	for rows.Next() {
		var i GetSubnetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Cidr,
			&i.GatewayIp,
			&i.NetworkID,
			&i.ProjectID,
			&i.EnableDhcp,
			&i.DnsNameservers,
			&i.SubnetpoolID,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
