CREATE TABLE
    `stack` (
        `id` varchar(36) NOT NULL,
        `created_at` datetime DEFAULT NULL,
        `updated_at` datetime DEFAULT NULL,
        `deleted_at` datetime DEFAULT NULL,
        `name` varchar(255) DEFAULT NULL,
        `raw_template_id` int NOT NULL,
        `prev_raw_template_id` int DEFAULT NULL,
        `user_creds_id` int DEFAULT NULL,
        `username` varchar(256) DEFAULT NULL,
        `owner_id` varchar(36) DEFAULT NULL,
        `action` varchar(255) DEFAULT NULL,
        `status` varchar(255) DEFAULT NULL,
        `status_reason` text,
        `timeout` int DEFAULT NULL,
        `tenant` varchar(256) DEFAULT NULL,
        `disable_rollback` tinyint(1) NOT NULL,
        `stack_user_project_id` varchar(64) DEFAULT NULL,
        `backup` tinyint(1) DEFAULT NULL,
        `nested_depth` int DEFAULT NULL,
        `convergence` tinyint(1) DEFAULT NULL,
        `current_traversal` varchar(36) DEFAULT NULL,
        `current_deps` longtext,
        `parent_resource_name` varchar(255) DEFAULT NULL,
        PRIMARY KEY (`id`),
        KEY `prev_raw_template_id` (`prev_raw_template_id`),
        KEY `raw_template_id` (`raw_template_id`),
        KEY `user_creds_id` (`user_creds_id`),
        KEY `ix_stack_name` (`name`),
        KEY `ix_stack_tenant` (`tenant`(255)),
        KEY `ix_stack_owner_id` (`owner_id`)
    );
