// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package ironic

import (
	"database/sql"
)

type Node struct {
	CreatedAt            sql.NullTime
	UpdatedAt            sql.NullTime
	ID                   int32
	Uuid                 sql.NullString
	InstanceUuid         sql.NullString
	ChassisID            sql.NullInt32
	PowerState           sql.NullString
	TargetPowerState     sql.NullString
	ProvisionState       sql.NullString
	TargetProvisionState sql.NullString
	LastError            sql.NullString
	Properties           sql.NullString
	Driver               sql.NullString
	DriverInfo           sql.NullString
	Reservation          sql.NullString
	Maintenance          sql.NullBool
	Extra                sql.NullString
	ProvisionUpdatedAt   sql.NullTime
	ConsoleEnabled       sql.NullBool
	InstanceInfo         sql.NullString
	ConductorAffinity    sql.NullInt32
	MaintenanceReason    sql.NullString
	DriverInternalInfo   sql.NullString
	Name                 sql.NullString
	InspectionStartedAt  sql.NullTime
	InspectionFinishedAt sql.NullTime
	CleanStep            sql.NullString
	RaidConfig           sql.NullString
	TargetRaidConfig     sql.NullString
	NetworkInterface     sql.NullString
	ResourceClass        sql.NullString
	BootInterface        sql.NullString
	ConsoleInterface     sql.NullString
	DeployInterface      sql.NullString
	InspectInterface     sql.NullString
	ManagementInterface  sql.NullString
	PowerInterface       sql.NullString
	RaidInterface        sql.NullString
	VendorInterface      sql.NullString
	StorageInterface     sql.NullString
	Version              sql.NullString
	RescueInterface      sql.NullString
	BiosInterface        sql.NullString
	Fault                sql.NullString
	DeployStep           sql.NullString
	ConductorGroup       string
	AutomatedClean       sql.NullBool
	Protected            bool
	ProtectedReason      sql.NullString
	Owner                sql.NullString
	AllocationID         sql.NullInt32
	Description          sql.NullString
	Retired              sql.NullBool
	RetiredReason        sql.NullString
	Lessee               sql.NullString
	NetworkData          sql.NullString
	BootMode             sql.NullString
	SecureBoot           sql.NullBool
	Shard                sql.NullString
	ParentNode           sql.NullString
	FirmwareInterface    sql.NullString
	ServiceStep          sql.NullString
}
