// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package ironic

import (
	"context"
	"database/sql"
)

const GetNodeMetrics = `-- name: GetNodeMetrics :many
SELECT 
    uuid,
    name,
    power_state,
    provision_state,
    maintenance,
    resource_class,
    console_enabled,
    retired,
    COALESCE(retired_reason, '') as retired_reason
FROM nodes
WHERE provision_state IS NULL OR provision_state != 'deleted'
`

type GetNodeMetricsRow struct {
	Uuid           sql.NullString
	Name           sql.NullString
	PowerState     sql.NullString
	ProvisionState sql.NullString
	Maintenance    sql.NullBool
	ResourceClass  sql.NullString
	ConsoleEnabled sql.NullBool
	Retired        sql.NullBool
	RetiredReason  string
}

func (q *Queries) GetNodeMetrics(ctx context.Context) ([]GetNodeMetricsRow, error) {
	rows, err := q.db.QueryContext(ctx, GetNodeMetrics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNodeMetricsRow
	for rows.Next() {
		var i GetNodeMetricsRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Name,
			&i.PowerState,
			&i.ProvisionState,
			&i.Maintenance,
			&i.ResourceClass,
			&i.ConsoleEnabled,
			&i.Retired,
			&i.RetiredReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
