// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package masakari

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type FailoverSegmentsRecoveryMethod string

const (
	FailoverSegmentsRecoveryMethodAuto         FailoverSegmentsRecoveryMethod = "auto"
	FailoverSegmentsRecoveryMethodReservedHost FailoverSegmentsRecoveryMethod = "reserved_host"
	FailoverSegmentsRecoveryMethodAutoPriority FailoverSegmentsRecoveryMethod = "auto_priority"
	FailoverSegmentsRecoveryMethodRhPriority   FailoverSegmentsRecoveryMethod = "rh_priority"
)

func (e *FailoverSegmentsRecoveryMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FailoverSegmentsRecoveryMethod(s)
	case string:
		*e = FailoverSegmentsRecoveryMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for FailoverSegmentsRecoveryMethod: %T", src)
	}
	return nil
}

type NullFailoverSegmentsRecoveryMethod struct {
	FailoverSegmentsRecoveryMethod FailoverSegmentsRecoveryMethod
	Valid                          bool // Valid is true if FailoverSegmentsRecoveryMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFailoverSegmentsRecoveryMethod) Scan(value interface{}) error {
	if value == nil {
		ns.FailoverSegmentsRecoveryMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FailoverSegmentsRecoveryMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFailoverSegmentsRecoveryMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FailoverSegmentsRecoveryMethod), nil
}

type NotificationsStatus string

const (
	NotificationsStatusNew      NotificationsStatus = "new"
	NotificationsStatusRunning  NotificationsStatus = "running"
	NotificationsStatusError    NotificationsStatus = "error"
	NotificationsStatusFailed   NotificationsStatus = "failed"
	NotificationsStatusIgnored  NotificationsStatus = "ignored"
	NotificationsStatusFinished NotificationsStatus = "finished"
)

func (e *NotificationsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationsStatus(s)
	case string:
		*e = NotificationsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationsStatus: %T", src)
	}
	return nil
}

type NullNotificationsStatus struct {
	NotificationsStatus NotificationsStatus
	Valid               bool // Valid is true if NotificationsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationsStatus), nil
}

type FailoverSegment struct {
	ID             int32
	Uuid           string
	Name           string
	ServiceType    string
	Enabled        bool
	Description    sql.NullString
	RecoveryMethod FailoverSegmentsRecoveryMethod
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	DeletedAt      sql.NullTime
	Deleted        bool
}

type Host struct {
	ID                int32
	Uuid              string
	Name              string
	Reserved          bool
	Type              string
	ControlAttributes string
	OnMaintenance     bool
	FailoverSegmentID string
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
	DeletedAt         sql.NullTime
	Deleted           bool
}

type Notification struct {
	ID                  int32
	NotificationUuid    string
	GeneratedTime       time.Time
	Type                string
	Payload             sql.NullString
	Status              NotificationsStatus
	SourceHostUuid      string
	FailoverSegmentUuid string
	Message             sql.NullString
	CreatedAt           sql.NullTime
	UpdatedAt           sql.NullTime
	DeletedAt           sql.NullTime
	Deleted             bool
}
