// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package masakari

import (
	"context"
	"database/sql"
)

const GetFailoverSegments = `-- name: GetFailoverSegments :many
SELECT
    id,
    uuid,
    name,
    service_type,
    enabled,
    description,
    recovery_method
FROM
    failover_segments
WHERE
    deleted = 0
`

type GetFailoverSegmentsRow struct {
	ID             int32
	Uuid           string
	Name           string
	ServiceType    string
	Enabled        bool
	Description    sql.NullString
	RecoveryMethod FailoverSegmentsRecoveryMethod
}

func (q *Queries) GetFailoverSegments(ctx context.Context) ([]GetFailoverSegmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, GetFailoverSegments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFailoverSegmentsRow
	for rows.Next() {
		var i GetFailoverSegmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.ServiceType,
			&i.Enabled,
			&i.Description,
			&i.RecoveryMethod,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetHosts = `-- name: GetHosts :many
SELECT
    h.id,
    h.uuid,
    h.name,
    h.reserved,
    h.type,
    h.control_attributes,
    h.on_maintenance,
    h.failover_segment_id,
    s.name AS failover_segment_name
FROM
    hosts h
    LEFT JOIN failover_segments s ON h.failover_segment_id = s.uuid
        AND s.deleted = 0
WHERE
    h.deleted = 0
`

type GetHostsRow struct {
	ID                  int32
	Uuid                string
	Name                string
	Reserved            bool
	Type                string
	ControlAttributes   string
	OnMaintenance       bool
	FailoverSegmentID   string
	FailoverSegmentName sql.NullString
}

func (q *Queries) GetHosts(ctx context.Context) ([]GetHostsRow, error) {
	rows, err := q.db.QueryContext(ctx, GetHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHostsRow
	for rows.Next() {
		var i GetHostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Reserved,
			&i.Type,
			&i.ControlAttributes,
			&i.OnMaintenance,
			&i.FailoverSegmentID,
			&i.FailoverSegmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetNotificationsByStatus = `-- name: GetNotificationsByStatus :many
SELECT
    status,
    COUNT(*) AS count
FROM
    notifications
WHERE
    deleted = 0
GROUP BY
    status
`

type GetNotificationsByStatusRow struct {
	Status NotificationsStatus
	Count  int64
}

func (q *Queries) GetNotificationsByStatus(ctx context.Context) ([]GetNotificationsByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, GetNotificationsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNotificationsByStatusRow
	for rows.Next() {
		var i GetNotificationsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
