-- Nova compute service database schema
-- This schema contains instances, compute nodes, and services tables

CREATE TABLE IF NOT EXISTS
    `instances` (
        `created_at` DATETIME NULL,
        `updated_at` DATETIME NULL,
        `deleted_at` DATETIME NULL,
        `id` INT NOT NULL AUTO_INCREMENT,
        `internal_id` INT NULL,
        `user_id` VARCHAR(255) NULL,
        `project_id` VARCHAR(255) NULL,
        `image_ref` VARCHAR(255) NULL,
        `kernel_id` VARCHAR(255) NULL,
        `ramdisk_id` VARCHAR(255) NULL,
        `launch_index` INT NULL,
        `key_name` VARCHAR(255) NULL,
        `key_data` MEDIUMTEXT NULL,
        `power_state` INT NULL,
        `vm_state` VARCHAR(255) NULL,
        `memory_mb` INT NULL,
        `vcpus` INT NULL,
        `hostname` VARCHAR(255) NULL,
        `host` VARCHAR(255) NULL,
        `user_data` MEDIUMTEXT NULL,
        `reservation_id` VARCHAR(255) NULL,
        `launched_at` DATETIME NULL,
        `terminated_at` DATETIME NULL,
        `display_name` VARCHAR(255) NULL,
        `display_description` VARCHAR(255) NULL,
        `availability_zone` VARCHAR(255) NULL,
        `locked` TINYINT(1) NULL,
        `os_type` VARCHAR(255) NULL,
        `launched_on` MEDIUMTEXT NULL,
        `instance_type_id` INT NULL,
        `vm_mode` VARCHAR(255) NULL,
        `uuid` VARCHAR(36) NOT NULL,
        `architecture` VARCHAR(255) NULL,
        `root_device_name` VARCHAR(255) NULL,
        `access_ip_v4` VARCHAR(39) NULL,
        `access_ip_v6` VARCHAR(39) NULL,
        `config_drive` VARCHAR(255) NULL,
        `task_state` VARCHAR(255) NULL,
        `default_ephemeral_device` VARCHAR(255) NULL,
        `default_swap_device` VARCHAR(255) NULL,
        `progress` INT NULL,
        `auto_disk_config` TINYINT(1) NULL,
        `shutdown_terminate` TINYINT(1) NULL,
        `disable_terminate` TINYINT(1) NULL,
        `root_gb` INT NULL,
        `ephemeral_gb` INT NULL,
        `cell_name` VARCHAR(255) NULL,
        `node` VARCHAR(255) NULL,
        `deleted` INT NULL,
        `locked_by` ENUM('owner','admin') NULL,
        `cleaned` INT NULL,
        `ephemeral_key_uuid` VARCHAR(36) NULL,
        `hidden` TINYINT(1) NULL,
        `compute_id` BIGINT NULL,
        PRIMARY KEY (`id`),
        UNIQUE KEY uniq_instances0uuid (`uuid`),
        KEY instances_project_id_deleted_idx (`project_id`, `deleted`),
        KEY instances_host_deleted_cleaned_idx (`host`, `deleted`, `cleaned`),
        KEY instances_uuid_deleted_idx (`uuid`, `deleted`)
    );

CREATE TABLE IF NOT EXISTS
    `services` (
        `created_at` DATETIME NULL,
        `updated_at` DATETIME NULL,
        `deleted_at` DATETIME NULL,
        `id` INT NOT NULL AUTO_INCREMENT,
        `host` VARCHAR(255) NULL,
        `binary` VARCHAR(255) NULL,
        `topic` VARCHAR(255) NULL,
        `report_count` INT NOT NULL,
        `disabled` TINYINT(1) NULL,
        `deleted` INT NULL,
        `disabled_reason` VARCHAR(255) NULL,
        `last_seen_up` DATETIME NULL,
        `forced_down` TINYINT(1) NULL,
        `version` INT NULL,
        `uuid` VARCHAR(36) NULL,
        PRIMARY KEY (`id`),
        UNIQUE KEY uniq_services0host0topic0deleted (`host`, `topic`, `deleted`),
        UNIQUE KEY uniq_services0host0binary0deleted (`host`, `binary`, `deleted`),
        UNIQUE KEY services_uuid_idx (`uuid`),
        KEY services_host_idx (`host`)
    );

CREATE TABLE IF NOT EXISTS
    `compute_nodes` (
        `created_at` DATETIME NULL,
        `updated_at` DATETIME NULL,
        `deleted_at` DATETIME NULL,
        `id` INT NOT NULL AUTO_INCREMENT,
        `service_id` INT NULL,
        `vcpus` INT NOT NULL,
        `memory_mb` INT NOT NULL,
        `local_gb` INT NOT NULL,
        `vcpus_used` INT NOT NULL,
        `memory_mb_used` INT NOT NULL,
        `local_gb_used` INT NOT NULL,
        `hypervisor_type` MEDIUMTEXT NOT NULL,
        `hypervisor_version` INT NOT NULL,
        `cpu_info` MEDIUMTEXT NOT NULL,
        `disk_available_least` INT NULL,
        `free_ram_mb` INT NULL,
        `free_disk_gb` INT NULL,
        `current_workload` INT NULL,
        `running_vms` INT NULL,
        `hypervisor_hostname` VARCHAR(255) NULL,
        `deleted` INT NULL,
        `host_ip` VARCHAR(39) NULL,
        `supported_instances` TEXT NULL,
        `pci_stats` TEXT NULL,
        `metrics` TEXT NULL,
        `extra_resources` TEXT NULL,
        `stats` TEXT NULL,
        `numa_topology` TEXT NULL,
        `host` VARCHAR(255) NULL,
        `ram_allocation_ratio` FLOAT NULL,
        `cpu_allocation_ratio` FLOAT NULL,
        `uuid` VARCHAR(36) NULL,
        `disk_allocation_ratio` FLOAT NULL,
        `mapped` INT NULL,
        PRIMARY KEY (`id`),
        UNIQUE KEY uniq_compute_nodes0host0hypervisor_hostname0deleted (`host`, `hypervisor_hostname`, `deleted`),
        UNIQUE KEY compute_nodes_uuid_idx (`uuid`)
    );
