// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package keystone

import (
	"database/sql"
)

type Group struct {
	ID          string
	DomainID    string
	Name        string
	Description sql.NullString
	Extra       sql.NullString
}

type Limit struct {
	InternalID        int32
	ID                string
	ProjectID         sql.NullString
	DomainID          sql.NullString
	ResourceLimit     int32
	Description       sql.NullString
	RegisteredLimitID sql.NullString
}

type Project struct {
	ID          string
	Name        string
	Extra       sql.NullString
	Description sql.NullString
	Enabled     sql.NullBool
	DomainID    string
	ParentID    sql.NullString
	IsDomain    bool
}

type ProjectTag struct {
	ProjectID string
	Name      string
}

type Region struct {
	ID             string
	Description    string
	ParentRegionID sql.NullString
	Extra          sql.NullString
}

type RegisteredLimit struct {
	InternalID   int32
	ID           string
	ServiceID    sql.NullString
	RegionID     sql.NullString
	ResourceName sql.NullString
	DefaultLimit int32
	Description  sql.NullString
}

type Service struct {
	ID      string
	Type    sql.NullString
	Enabled sql.NullBool
	Extra   sql.NullString
}

type User struct {
	ID               string
	Extra            sql.NullString
	Enabled          sql.NullBool
	DefaultProjectID sql.NullString
	CreatedAt        sql.NullTime
	LastActiveAt     sql.NullTime
	DomainID         string
}
