// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package nova_api

import (
	"database/sql"
)

type Aggregate struct {
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	ID        int32
	Uuid      sql.NullString
	Name      sql.NullString
}

type AggregateHost struct {
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	ID          int32
	Host        sql.NullString
	AggregateID int32
}

type Flavor struct {
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	Name        string
	ID          int32
	MemoryMb    int32
	Vcpus       int32
	Swap        int32
	VcpuWeight  sql.NullInt32
	Flavorid    string
	RxtxFactor  sql.NullFloat64
	RootGb      sql.NullInt32
	EphemeralGb sql.NullInt32
	Disabled    sql.NullBool
	IsPublic    sql.NullBool
	Description sql.NullString
}

type Quota struct {
	ID        int32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	ProjectID sql.NullString
	Resource  string
	HardLimit sql.NullInt32
}

type QuotaUsage struct {
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	ID           int32
	ProjectID    sql.NullString
	UserID       sql.NullString
	Resource     string
	InUse        int32
	Reserved     int32
	UntilRefresh sql.NullInt32
}
