// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package placement

import (
	"database/sql"
)

type Allocation struct {
	ID                 int32
	ResourceProviderID int32
	ConsumerID         string
	ResourceClassID    int32
	Used               int32
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
}

type Consumer struct {
	ID             int32
	Uuid           string
	ProjectID      int32
	UserID         int32
	Generation     int32
	ConsumerTypeID sql.NullInt32
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type Inventory struct {
	ID                 int32
	ResourceProviderID int32
	ResourceClassID    int32
	Total              int32
	Reserved           int32
	MinUnit            int32
	MaxUnit            int32
	StepSize           int32
	AllocationRatio    string
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
}

type Project struct {
	ID         int32
	ExternalID string
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type ResourceClass struct {
	ID        int32
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type ResourceProvider struct {
	ID               int32
	Uuid             string
	Name             sql.NullString
	Generation       int32
	CanHost          int32
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
	RootProviderID   int32
	ParentProviderID sql.NullInt32
}

type User struct {
	ID         int32
	ExternalID string
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}
