// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package heat

import (
	"database/sql"
)

type Stack struct {
	ID                 string
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
	DeletedAt          sql.NullTime
	Name               sql.NullString
	RawTemplateID      int32
	PrevRawTemplateID  sql.NullInt32
	UserCredsID        sql.NullInt32
	Username           sql.NullString
	OwnerID            sql.NullString
	Action             sql.NullString
	Status             sql.NullString
	StatusReason       sql.NullString
	Timeout            sql.NullInt32
	Tenant             sql.NullString
	DisableRollback    bool
	StackUserProjectID sql.NullString
	Backup             sql.NullBool
	NestedDepth        sql.NullInt32
	Convergence        sql.NullBool
	CurrentTraversal   sql.NullString
	CurrentDeps        sql.NullString
	ParentResourceName sql.NullString
}
