// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package heat

import (
	"context"
	"database/sql"
)

const GetStackMetrics = `-- name: GetStackMetrics :many
SELECT 
    s.id,
    COALESCE(s.name, '') as name,
    COALESCE(s.status, '') as status,
    COALESCE(s.action, '') as action,
    COALESCE(s.tenant, '') as tenant,
    s.created_at,
    s.updated_at,
    s.deleted_at,
    COALESCE(s.nested_depth, 0) as nested_depth,
    COALESCE(s.disable_rollback, false) as disable_rollback
FROM stack s
WHERE s.deleted_at IS NULL
ORDER BY s.created_at DESC
`

type GetStackMetricsRow struct {
	ID              string
	Name            string
	Status          string
	Action          string
	Tenant          string
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	DeletedAt       sql.NullTime
	NestedDepth     int32
	DisableRollback bool
}

func (q *Queries) GetStackMetrics(ctx context.Context) ([]GetStackMetricsRow, error) {
	rows, err := q.db.QueryContext(ctx, GetStackMetrics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStackMetricsRow
	for rows.Next() {
		var i GetStackMetricsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.Action,
			&i.Tenant,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.NestedDepth,
			&i.DisableRollback,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
