// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package designate

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type RecordsAction string

const (
	RecordsActionCREATE RecordsAction = "CREATE"
	RecordsActionDELETE RecordsAction = "DELETE"
	RecordsActionUPDATE RecordsAction = "UPDATE"
	RecordsActionNONE   RecordsAction = "NONE"
)

func (e *RecordsAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RecordsAction(s)
	case string:
		*e = RecordsAction(s)
	default:
		return fmt.Errorf("unsupported scan type for RecordsAction: %T", src)
	}
	return nil
}

type NullRecordsAction struct {
	RecordsAction RecordsAction
	Valid         bool // Valid is true if RecordsAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRecordsAction) Scan(value interface{}) error {
	if value == nil {
		ns.RecordsAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RecordsAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRecordsAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RecordsAction), nil
}

type RecordsStatus string

const (
	RecordsStatusACTIVE  RecordsStatus = "ACTIVE"
	RecordsStatusPENDING RecordsStatus = "PENDING"
	RecordsStatusDELETED RecordsStatus = "DELETED"
	RecordsStatusERROR   RecordsStatus = "ERROR"
)

func (e *RecordsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RecordsStatus(s)
	case string:
		*e = RecordsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RecordsStatus: %T", src)
	}
	return nil
}

type NullRecordsStatus struct {
	RecordsStatus RecordsStatus
	Valid         bool // Valid is true if RecordsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRecordsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RecordsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RecordsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRecordsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RecordsStatus), nil
}

type RecordsetsType string

const (
	RecordsetsTypeA     RecordsetsType = "A"
	RecordsetsTypeAAAA  RecordsetsType = "AAAA"
	RecordsetsTypeCNAME RecordsetsType = "CNAME"
	RecordsetsTypeMX    RecordsetsType = "MX"
	RecordsetsTypeSRV   RecordsetsType = "SRV"
	RecordsetsTypeTXT   RecordsetsType = "TXT"
	RecordsetsTypeSPF   RecordsetsType = "SPF"
	RecordsetsTypeNS    RecordsetsType = "NS"
	RecordsetsTypePTR   RecordsetsType = "PTR"
	RecordsetsTypeSSHFP RecordsetsType = "SSHFP"
	RecordsetsTypeSOA   RecordsetsType = "SOA"
	RecordsetsTypeNAPTR RecordsetsType = "NAPTR"
	RecordsetsTypeCAA   RecordsetsType = "CAA"
	RecordsetsTypeCERT  RecordsetsType = "CERT"
	RecordsetsTypeHTTPS RecordsetsType = "HTTPS"
	RecordsetsTypeSVCB  RecordsetsType = "SVCB"
	RecordsetsTypeTLSA  RecordsetsType = "TLSA"
)

func (e *RecordsetsType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RecordsetsType(s)
	case string:
		*e = RecordsetsType(s)
	default:
		return fmt.Errorf("unsupported scan type for RecordsetsType: %T", src)
	}
	return nil
}

type NullRecordsetsType struct {
	RecordsetsType RecordsetsType
	Valid          bool // Valid is true if RecordsetsType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRecordsetsType) Scan(value interface{}) error {
	if value == nil {
		ns.RecordsetsType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RecordsetsType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRecordsetsType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RecordsetsType), nil
}

type ZonesAction string

const (
	ZonesActionCREATE ZonesAction = "CREATE"
	ZonesActionDELETE ZonesAction = "DELETE"
	ZonesActionUPDATE ZonesAction = "UPDATE"
	ZonesActionNONE   ZonesAction = "NONE"
)

func (e *ZonesAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ZonesAction(s)
	case string:
		*e = ZonesAction(s)
	default:
		return fmt.Errorf("unsupported scan type for ZonesAction: %T", src)
	}
	return nil
}

type NullZonesAction struct {
	ZonesAction ZonesAction
	Valid       bool // Valid is true if ZonesAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullZonesAction) Scan(value interface{}) error {
	if value == nil {
		ns.ZonesAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ZonesAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullZonesAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ZonesAction), nil
}

type ZonesStatus string

const (
	ZonesStatusACTIVE  ZonesStatus = "ACTIVE"
	ZonesStatusPENDING ZonesStatus = "PENDING"
	ZonesStatusDELETED ZonesStatus = "DELETED"
	ZonesStatusERROR   ZonesStatus = "ERROR"
)

func (e *ZonesStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ZonesStatus(s)
	case string:
		*e = ZonesStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ZonesStatus: %T", src)
	}
	return nil
}

type NullZonesStatus struct {
	ZonesStatus ZonesStatus
	Valid       bool // Valid is true if ZonesStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullZonesStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ZonesStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ZonesStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullZonesStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ZonesStatus), nil
}

type ZonesType string

const (
	ZonesTypePRIMARY   ZonesType = "PRIMARY"
	ZonesTypeSECONDARY ZonesType = "SECONDARY"
	ZonesTypeCATALOG   ZonesType = "CATALOG"
)

func (e *ZonesType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ZonesType(s)
	case string:
		*e = ZonesType(s)
	default:
		return fmt.Errorf("unsupported scan type for ZonesType: %T", src)
	}
	return nil
}

type NullZonesType struct {
	ZonesType ZonesType
	Valid     bool // Valid is true if ZonesType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullZonesType) Scan(value interface{}) error {
	if value == nil {
		ns.ZonesType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ZonesType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullZonesType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ZonesType), nil
}

type Record struct {
	ID                    string
	Version               int32
	CreatedAt             sql.NullTime
	UpdatedAt             sql.NullTime
	RecordsetID           string
	Data                  string
	Description           sql.NullString
	Hash                  sql.NullString
	Managed               bool
	ManagedResourceType   sql.NullString
	ManagedResourceRegion sql.NullString
	ManagedResourceID     sql.NullString
	ManagedTenantID       sql.NullString
	Status                RecordsStatus
	TenantID              sql.NullString
	ZoneID                string
	Action                RecordsAction
	Serial                int32
}

type Recordset struct {
	ID          string
	Version     int32
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	ZoneShard   int16
	TenantID    sql.NullString
	ZoneID      string
	Name        string
	Type        RecordsetsType
	Ttl         sql.NullInt32
	Description sql.NullString
	ReverseName string
}

type Zone struct {
	ID              string
	Version         int32
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	Deleted         string
	DeletedAt       sql.NullTime
	Shard           int16
	TenantID        sql.NullString
	Name            string
	Email           string
	Description     sql.NullString
	Type            ZonesType
	TransferredAt   sql.NullTime
	Ttl             int32
	Serial          int32
	Refresh         int32
	Retry           int32
	Expire          int32
	Minimum         int32
	Status          ZonesStatus
	ParentZoneID    sql.NullString
	Action          ZonesAction
	PoolID          sql.NullString
	ReverseName     string
	DelayedNotify   bool
	IncrementSerial bool
}
