// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package designate

import (
	"context"
	"database/sql"
)

const GetRecordsets = `-- name: GetRecordsets :many
SELECT DISTINCT
    r.id,
    r.name,
    r.type,
    r.zone_id,
    z.name AS zone_name,
    r.tenant_id,
    COALESCE(
        (SELECT rec.status FROM records rec
         WHERE rec.recordset_id = r.id
         ORDER BY FIELD(rec.status, 'ERROR', 'PENDING', 'DELETED', 'ACTIVE') DESC
         LIMIT 1),
        'PENDING'
    ) AS status
FROM
    recordsets r
    INNER JOIN zones z ON r.zone_id = z.id AND z.deleted = '0'
`

type GetRecordsetsRow struct {
	ID       string
	Name     string
	Type     RecordsetsType
	ZoneID   string
	ZoneName string
	TenantID sql.NullString
	Status   interface{}
}

func (q *Queries) GetRecordsets(ctx context.Context) ([]GetRecordsetsRow, error) {
	rows, err := q.db.QueryContext(ctx, GetRecordsets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecordsetsRow
	for rows.Next() {
		var i GetRecordsetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.ZoneID,
			&i.ZoneName,
			&i.TenantID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetZones = `-- name: GetZones :many
SELECT
    id,
    name,
    tenant_id,
    type,
    status
FROM
    zones
WHERE
    deleted = '0'
`

type GetZonesRow struct {
	ID       string
	Name     string
	TenantID sql.NullString
	Type     ZonesType
	Status   ZonesStatus
}

func (q *Queries) GetZones(ctx context.Context) ([]GetZonesRow, error) {
	rows, err := q.db.QueryContext(ctx, GetZones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetZonesRow
	for rows.Next() {
		var i GetZonesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TenantID,
			&i.Type,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
