// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package magnum

import (
	"database/sql"
)

type Cluster struct {
	CreatedAt           sql.NullTime
	UpdatedAt           sql.NullTime
	ID                  int32
	Uuid                sql.NullString
	Name                sql.NullString
	ClusterTemplateID   sql.NullString
	ApiAddress          sql.NullString
	StackID             sql.NullString
	ProjectID           sql.NullString
	UserID              sql.NullString
	Status              sql.NullString
	DiscoveryUrl        sql.NullString
	StatusReason        sql.NullString
	CaCertRef           sql.NullString
	MagnumCertRef       sql.NullString
	CreateTimeout       sql.NullInt32
	TrustID             sql.NullString
	TrusteeUsername     sql.NullString
	TrusteeUserID       sql.NullString
	TrusteePassword     sql.NullString
	CoeVersion          sql.NullString
	ContainerVersion    sql.NullString
	Keypair             sql.NullString
	DockerVolumeSize    sql.NullInt32
	Labels              sql.NullString
	MasterFlavorID      sql.NullString
	FlavorID            sql.NullString
	HealthStatus        sql.NullString
	HealthStatusReason  sql.NullString
	FixedNetwork        sql.NullString
	FixedSubnet         sql.NullString
	FloatingIpEnabled   sql.NullBool
	MasterLbEnabled     sql.NullBool
	EtcdCaCertRef       sql.NullString
	FrontProxyCaCertRef sql.NullString
}

type Nodegroup struct {
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
	ID               int32
	Uuid             string
	Name             string
	ClusterID        string
	ProjectID        string
	DockerVolumeSize sql.NullInt32
	Labels           sql.NullString
	FlavorID         sql.NullString
	ImageID          sql.NullString
	NodeAddresses    sql.NullString
	NodeCount        sql.NullInt32
	MaxNodeCount     sql.NullInt32
	MinNodeCount     sql.NullInt32
	Role             sql.NullString
	IsDefault        sql.NullBool
	StackID          sql.NullString
	Status           sql.NullString
	StatusReason     sql.NullString
	Version          sql.NullString
}
