CREATE TABLE
    `nodes` (
        `created_at` DATETIME,
        `updated_at` DATETIME,
        `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        `uuid` VARCHAR(36) UNIQUE,
        `instance_uuid` VARCHAR(36) UNIQUE,
        `chassis_id` INT,
        `power_state` VARCHAR(15),
        `target_power_state` VARCHAR(15),
        `provision_state` VARCHAR(15),
        `target_provision_state` VARCHAR(15),
        `last_error` TEXT,
        `properties` TEXT,
        `driver` VARCHAR(255),
        `driver_info` TEXT,
        `reservation` VARCHAR(255),
        `maintenance` TINYINT(1),
        `extra` TEXT,
        `provision_updated_at` DATETIME,
        `console_enabled` TINYINT(1),
        `instance_info` LONGTEXT,
        `conductor_affinity` INT,
        `maintenance_reason` TEXT,
        `driver_internal_info` TEXT,
        `name` VARCHAR(255) UNIQUE,
        `inspection_started_at` DATETIME,
        `inspection_finished_at` DATETIME,
        `clean_step` TEXT,
        `raid_config` TEXT,
        `target_raid_config` TEXT,
        `network_interface` VARCHAR(255),
        `resource_class` VARCHAR(80),
        `boot_interface` VARCHAR(255),
        `console_interface` VARCHAR(255),
        `deploy_interface` VARCHAR(255),
        `inspect_interface` VARCHAR(255),
        `management_interface` VARCHAR(255),
        `power_interface` VARCHAR(255),
        `raid_interface` VARCHAR(255),
        `vendor_interface` VARCHAR(255),
        `storage_interface` VARCHAR(255),
        `version` VARCHAR(15),
        `rescue_interface` VARCHAR(255),
        `bios_interface` VARCHAR(255),
        `fault` VARCHAR(255),
        `deploy_step` TEXT,
        `conductor_group` VARCHAR(255) NOT NULL DEFAULT '',
        `automated_clean` TINYINT(1),
        `protected` TINYINT(1) NOT NULL DEFAULT 0,
        `protected_reason` TEXT,
        `owner` VARCHAR(255),
        `allocation_id` INT,
        `description` TEXT,
        `retired` TINYINT(1) DEFAULT 0,
        `retired_reason` TEXT,
        `lessee` VARCHAR(255),
        `network_data` TEXT,
        `boot_mode` VARCHAR(16),
        `secure_boot` TINYINT(1),
        `shard` VARCHAR(255),
        `parent_node` VARCHAR(36),
        `firmware_interface` VARCHAR(255),
        `service_step` TEXT,
        INDEX `chassis_id_idx` (`chassis_id`),
        INDEX `conductor_affinity_idx` (`conductor_affinity`),
        INDEX `allocation_id_idx` (`allocation_id`),
        INDEX `reservation_idx` (`reservation`),
        INDEX `driver_idx` (`driver`),
        INDEX `owner_idx` (`owner`),
        INDEX `lessee_idx` (`lessee`),
        INDEX `provision_state_idx` (`provision_state`),
        INDEX `conductor_group_idx` (`conductor_group`),
        INDEX `resource_class_idx` (`resource_class`),
        INDEX `shard_idx` (`shard`),
        INDEX `parent_node_idx` (`parent_node`)
    );
