// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package nova

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type InstancesLockedBy string

const (
	InstancesLockedByOwner InstancesLockedBy = "owner"
	InstancesLockedByAdmin InstancesLockedBy = "admin"
)

func (e *InstancesLockedBy) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InstancesLockedBy(s)
	case string:
		*e = InstancesLockedBy(s)
	default:
		return fmt.Errorf("unsupported scan type for InstancesLockedBy: %T", src)
	}
	return nil
}

type NullInstancesLockedBy struct {
	InstancesLockedBy InstancesLockedBy
	Valid             bool // Valid is true if InstancesLockedBy is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInstancesLockedBy) Scan(value interface{}) error {
	if value == nil {
		ns.InstancesLockedBy, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InstancesLockedBy.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInstancesLockedBy) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InstancesLockedBy), nil
}

type ComputeNode struct {
	CreatedAt           sql.NullTime
	UpdatedAt           sql.NullTime
	DeletedAt           sql.NullTime
	ID                  int32
	ServiceID           sql.NullInt32
	Vcpus               int32
	MemoryMb            int32
	LocalGb             int32
	VcpusUsed           int32
	MemoryMbUsed        int32
	LocalGbUsed         int32
	HypervisorType      string
	HypervisorVersion   int32
	CpuInfo             string
	DiskAvailableLeast  sql.NullInt32
	FreeRamMb           sql.NullInt32
	FreeDiskGb          sql.NullInt32
	CurrentWorkload     sql.NullInt32
	RunningVms          sql.NullInt32
	HypervisorHostname  sql.NullString
	Deleted             sql.NullInt32
	HostIp              sql.NullString
	SupportedInstances  sql.NullString
	PciStats            sql.NullString
	Metrics             sql.NullString
	ExtraResources      sql.NullString
	Stats               sql.NullString
	NumaTopology        sql.NullString
	Host                sql.NullString
	RamAllocationRatio  sql.NullFloat64
	CpuAllocationRatio  sql.NullFloat64
	Uuid                sql.NullString
	DiskAllocationRatio sql.NullFloat64
	Mapped              sql.NullInt32
}

type Instance struct {
	CreatedAt              sql.NullTime
	UpdatedAt              sql.NullTime
	DeletedAt              sql.NullTime
	ID                     int32
	InternalID             sql.NullInt32
	UserID                 sql.NullString
	ProjectID              sql.NullString
	ImageRef               sql.NullString
	KernelID               sql.NullString
	RamdiskID              sql.NullString
	LaunchIndex            sql.NullInt32
	KeyName                sql.NullString
	KeyData                sql.NullString
	PowerState             sql.NullInt32
	VmState                sql.NullString
	MemoryMb               sql.NullInt32
	Vcpus                  sql.NullInt32
	Hostname               sql.NullString
	Host                   sql.NullString
	UserData               sql.NullString
	ReservationID          sql.NullString
	LaunchedAt             sql.NullTime
	TerminatedAt           sql.NullTime
	DisplayName            sql.NullString
	DisplayDescription     sql.NullString
	AvailabilityZone       sql.NullString
	Locked                 sql.NullBool
	OsType                 sql.NullString
	LaunchedOn             sql.NullString
	InstanceTypeID         sql.NullInt32
	VmMode                 sql.NullString
	Uuid                   string
	Architecture           sql.NullString
	RootDeviceName         sql.NullString
	AccessIpV4             sql.NullString
	AccessIpV6             sql.NullString
	ConfigDrive            sql.NullString
	TaskState              sql.NullString
	DefaultEphemeralDevice sql.NullString
	DefaultSwapDevice      sql.NullString
	Progress               sql.NullInt32
	AutoDiskConfig         sql.NullBool
	ShutdownTerminate      sql.NullBool
	DisableTerminate       sql.NullBool
	RootGb                 sql.NullInt32
	EphemeralGb            sql.NullInt32
	CellName               sql.NullString
	Node                   sql.NullString
	Deleted                sql.NullInt32
	LockedBy               NullInstancesLockedBy
	Cleaned                sql.NullInt32
	EphemeralKeyUuid       sql.NullString
	Hidden                 sql.NullBool
	ComputeID              sql.NullInt64
}

type Service struct {
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	DeletedAt      sql.NullTime
	ID             int32
	Host           sql.NullString
	Binary         sql.NullString
	Topic          sql.NullString
	ReportCount    int32
	Disabled       sql.NullBool
	Deleted        sql.NullInt32
	DisabledReason sql.NullString
	LastSeenUp     sql.NullTime
	ForcedDown     sql.NullBool
	Version        sql.NullInt32
	Uuid           sql.NullString
}
