// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package nova

import (
	"context"
	"database/sql"
)

const GetComputeNodes = `-- name: GetComputeNodes :many
SELECT 
    id,
    uuid,
    host,
    hypervisor_hostname,
    hypervisor_type,
    hypervisor_version,
    vcpus,
    vcpus_used,
    memory_mb,
    memory_mb_used,
    local_gb,
    local_gb_used,
    disk_available_least,
    free_ram_mb,
    free_disk_gb,
    current_workload,
    running_vms,
    cpu_allocation_ratio,
    ram_allocation_ratio,
    disk_allocation_ratio,
    deleted
FROM compute_nodes
WHERE deleted = 0
`

type GetComputeNodesRow struct {
	ID                  int32
	Uuid                sql.NullString
	Host                sql.NullString
	HypervisorHostname  sql.NullString
	HypervisorType      string
	HypervisorVersion   int32
	Vcpus               int32
	VcpusUsed           int32
	MemoryMb            int32
	MemoryMbUsed        int32
	LocalGb             int32
	LocalGbUsed         int32
	DiskAvailableLeast  sql.NullInt32
	FreeRamMb           sql.NullInt32
	FreeDiskGb          sql.NullInt32
	CurrentWorkload     sql.NullInt32
	RunningVms          sql.NullInt32
	CpuAllocationRatio  sql.NullFloat64
	RamAllocationRatio  sql.NullFloat64
	DiskAllocationRatio sql.NullFloat64
	Deleted             sql.NullInt32
}

func (q *Queries) GetComputeNodes(ctx context.Context) ([]GetComputeNodesRow, error) {
	rows, err := q.db.QueryContext(ctx, GetComputeNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetComputeNodesRow
	for rows.Next() {
		var i GetComputeNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Host,
			&i.HypervisorHostname,
			&i.HypervisorType,
			&i.HypervisorVersion,
			&i.Vcpus,
			&i.VcpusUsed,
			&i.MemoryMb,
			&i.MemoryMbUsed,
			&i.LocalGb,
			&i.LocalGbUsed,
			&i.DiskAvailableLeast,
			&i.FreeRamMb,
			&i.FreeDiskGb,
			&i.CurrentWorkload,
			&i.RunningVms,
			&i.CpuAllocationRatio,
			&i.RamAllocationRatio,
			&i.DiskAllocationRatio,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetInstances = `-- name: GetInstances :many
SELECT 
    id,
    uuid,
    display_name,
    user_id,
    project_id,
    host,
    availability_zone,
    vm_state,
    power_state,
    task_state,
    memory_mb,
    vcpus,
    root_gb,
    ephemeral_gb,
    launched_at,
    terminated_at,
    instance_type_id,
    deleted
FROM instances
WHERE deleted = 0
`

type GetInstancesRow struct {
	ID               int32
	Uuid             string
	DisplayName      sql.NullString
	UserID           sql.NullString
	ProjectID        sql.NullString
	Host             sql.NullString
	AvailabilityZone sql.NullString
	VmState          sql.NullString
	PowerState       sql.NullInt32
	TaskState        sql.NullString
	MemoryMb         sql.NullInt32
	Vcpus            sql.NullInt32
	RootGb           sql.NullInt32
	EphemeralGb      sql.NullInt32
	LaunchedAt       sql.NullTime
	TerminatedAt     sql.NullTime
	InstanceTypeID   sql.NullInt32
	Deleted          sql.NullInt32
}

func (q *Queries) GetInstances(ctx context.Context) ([]GetInstancesRow, error) {
	rows, err := q.db.QueryContext(ctx, GetInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInstancesRow
	for rows.Next() {
		var i GetInstancesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.DisplayName,
			&i.UserID,
			&i.ProjectID,
			&i.Host,
			&i.AvailabilityZone,
			&i.VmState,
			&i.PowerState,
			&i.TaskState,
			&i.MemoryMb,
			&i.Vcpus,
			&i.RootGb,
			&i.EphemeralGb,
			&i.LaunchedAt,
			&i.TerminatedAt,
			&i.InstanceTypeID,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetServices = `-- name: GetServices :many
SELECT 
    id,
    uuid,
    host,
    ` + "`" + `binary` + "`" + `,
    topic,
    disabled,
    disabled_reason,
    last_seen_up,
    forced_down,
    version,
    report_count,
    deleted
FROM services
WHERE deleted = 0
`

type GetServicesRow struct {
	ID             int32
	Uuid           sql.NullString
	Host           sql.NullString
	Binary         sql.NullString
	Topic          sql.NullString
	Disabled       sql.NullBool
	DisabledReason sql.NullString
	LastSeenUp     sql.NullTime
	ForcedDown     sql.NullBool
	Version        sql.NullInt32
	ReportCount    int32
	Deleted        sql.NullInt32
}

func (q *Queries) GetServices(ctx context.Context) ([]GetServicesRow, error) {
	rows, err := q.db.QueryContext(ctx, GetServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetServicesRow
	for rows.Next() {
		var i GetServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Host,
			&i.Binary,
			&i.Topic,
			&i.Disabled,
			&i.DisabledReason,
			&i.LastSeenUp,
			&i.ForcedDown,
			&i.Version,
			&i.ReportCount,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
