// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package octavia

import (
	"database/sql"
)

type Amphora struct {
	ID             string
	ComputeID      sql.NullString
	Status         string
	LoadBalancerID sql.NullString
	LbNetworkIp    sql.NullString
	HaIp           sql.NullString
	Role           sql.NullString
	CertExpiration sql.NullTime
}

type LoadBalancer struct {
	ProjectID          sql.NullString
	ID                 string
	Name               sql.NullString
	ProvisioningStatus string
	OperatingStatus    string
	Provider           sql.NullString
}

type Pool struct {
	ProjectID          sql.NullString
	ID                 string
	Name               sql.NullString
	Protocol           string
	LbAlgorithm        string
	OperatingStatus    string
	LoadBalancerID     sql.NullString
	ProvisioningStatus string
}

type Vip struct {
	LoadBalancerID string
	IpAddress      sql.NullString
}
