// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package glance

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type ImagesVisibility string

const (
	ImagesVisibilityPrivate   ImagesVisibility = "private"
	ImagesVisibilityPublic    ImagesVisibility = "public"
	ImagesVisibilityShared    ImagesVisibility = "shared"
	ImagesVisibilityCommunity ImagesVisibility = "community"
)

func (e *ImagesVisibility) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ImagesVisibility(s)
	case string:
		*e = ImagesVisibility(s)
	default:
		return fmt.Errorf("unsupported scan type for ImagesVisibility: %T", src)
	}
	return nil
}

type NullImagesVisibility struct {
	ImagesVisibility ImagesVisibility
	Valid            bool // Valid is true if ImagesVisibility is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullImagesVisibility) Scan(value interface{}) error {
	if value == nil {
		ns.ImagesVisibility, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ImagesVisibility.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullImagesVisibility) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ImagesVisibility), nil
}

type Image struct {
	ID              string
	Name            sql.NullString
	Size            sql.NullInt64
	Status          string
	CreatedAt       time.Time
	UpdatedAt       sql.NullTime
	DeletedAt       sql.NullTime
	Deleted         bool
	DiskFormat      sql.NullString
	ContainerFormat sql.NullString
	Checksum        sql.NullString
	Owner           sql.NullString
	MinDisk         int32
	MinRam          int32
	Protected       bool
	VirtualSize     sql.NullInt64
	Visibility      ImagesVisibility
	OsHidden        bool
	OsHashAlgo      sql.NullString
	OsHashValue     sql.NullString
}
