CREATE TABLE
    `cluster` (
        `created_at` datetime DEFAULT NULL,
        `updated_at` datetime DEFAULT NULL,
        `id` int NOT NULL AUTO_INCREMENT,
        `uuid` varchar(36) DEFAULT NULL,
        `name` varchar(255) DEFAULT NULL,
        `cluster_template_id` varchar(255) DEFAULT NULL,
        `api_address` varchar(255) DEFAULT NULL,
        `stack_id` varchar(255) DEFAULT NULL,
        `project_id` varchar(255) DEFAULT NULL,
        `user_id` varchar(255) DEFAULT NULL,
        `status` varchar(20) DEFAULT NULL,
        `discovery_url` varchar(255) DEFAULT NULL,
        `status_reason` text,
        `ca_cert_ref` varchar(512) DEFAULT NULL,
        `magnum_cert_ref` varchar(512) DEFAULT NULL,
        `create_timeout` int DEFAULT NULL,
        `trust_id` varchar(255) DEFAULT NULL,
        `trustee_username` varchar(255) DEFAULT NULL,
        `trustee_user_id` varchar(255) DEFAULT NULL,
        `trustee_password` varchar(255) DEFAULT NULL,
        `coe_version` varchar(255) DEFAULT NULL,
        `container_version` varchar(255) DEFAULT NULL,
        `keypair` varchar(255) DEFAULT NULL,
        `docker_volume_size` int DEFAULT NULL,
        `labels` text,
        `master_flavor_id` varchar(255) DEFAULT NULL,
        `flavor_id` varchar(255) DEFAULT NULL,
        `health_status` varchar(20) DEFAULT NULL,
        `health_status_reason` text,
        `fixed_network` varchar(255) DEFAULT NULL,
        `fixed_subnet` varchar(255) DEFAULT NULL,
        `floating_ip_enabled` tinyint(1) DEFAULT NULL,
        `master_lb_enabled` tinyint(1) DEFAULT NULL,
        `etcd_ca_cert_ref` varchar(512) DEFAULT NULL,
        `front_proxy_ca_cert_ref` varchar(512) DEFAULT NULL,
        PRIMARY KEY (`id`),
        UNIQUE KEY `uniq_bay0uuid` (`uuid`)
);

CREATE TABLE
    `nodegroup` (
        `created_at` datetime DEFAULT NULL,
        `updated_at` datetime DEFAULT NULL,
        `id` int NOT NULL AUTO_INCREMENT,
        `uuid` varchar(36) NOT NULL,
        `name` varchar(255) NOT NULL,
        `cluster_id` varchar(255) NOT NULL,
        `project_id` varchar(255) NOT NULL,
        `docker_volume_size` int DEFAULT NULL,
        `labels` text,
        `flavor_id` varchar(255) DEFAULT NULL,
        `image_id` varchar(255) DEFAULT NULL,
        `node_addresses` text,
        `node_count` int DEFAULT NULL,
        `max_node_count` int DEFAULT NULL,
        `min_node_count` int DEFAULT NULL,
        `role` varchar(255) DEFAULT NULL,
        `is_default` tinyint(1) DEFAULT NULL,
        `stack_id` varchar(255) DEFAULT NULL,
        `status` varchar(20) DEFAULT NULL,
        `status_reason` text,
        `version` varchar(20) DEFAULT NULL,
        PRIMARY KEY (`id`),
        UNIQUE KEY `uniq_nodegroup0uuid` (`uuid`),
        UNIQUE KEY `uniq_nodegroup0cluster_id0name` (`cluster_id`,`name`)
);
