name: periodic

on:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - uses: vexxhost/github-actions/scan-image@377e35d3a5c570338901d9e0edf48bcf86c7c9ef # main
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/openstack-database-exporter:edge
