name: release

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Run "release-please"
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: go

      - name: Checkout project
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        if: ${{ steps.release.outputs.release_created }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        if: ${{ steps.release.outputs.release_created }}
        uses: docker/bake-action@v4
        with:
          push: true
        env:
          TAG: ${{ steps.release.outputs.tag_name }}
